### ISSUE TITLE
OpenWRT

### ISSUE THREAD

**Issue by indewer** [Anonym-tsk/tpws-keenetic#10]
можно ли как-нибудь перенести эту структуру для роутеров с OpenWRT?

**Comment by Anonym-tsk** [comment]
Вроде оно и так должно работать под OpenWRT. Есть там /opt?

**Comment by Anonym-tsk** [comment]
Удалось подружить с OpenWRT?

**Comment by dartraiden** [comment]
В OpenWrt инит-скрипты лежат в /etc/init.d

/opt там или пустой, или его вообще нет, не помню

Автозапуска скриптов по событиям (/etc/ndm/) там тоже нет.
