### ISSUE TITLE
[BUG] При запущенном tpws не обновляется прошивка OpenWRT сетевого диска WD My Book Live

### ISSUE THREAD

**Issue by Seamas73** [Anonym-tsk/tpws-keenetic#18]
При запущенном tpws не обновляется прошивка OpenWRT сетевого диска WD My Book Live: при попытке обновить списки пакетов из веб-интерфейса админки сетевого диска или при запуске в ssh-консоли команды opkg update  получаю ответ:
```
opkg_download: Failed to download https://downloads.openwrt.org/releases/23.05.4/.../.../Packages.gz, wget returned 4.
opkg_download: Check your network settings and connectivity
```
для каждого источника пакетов. Пробовал также режимы работы all и auto. С тем же результатом
Стоит остановить сервис tpws, как обновление списка пакетов проходит без ошибок.

Сервис tpws используется на роутере Keenetic Giga AX (KN-1011)? с прошивкой 4.2 beta 2

Провайдер  Дом.Ру, СПб, подключение IPoE

```
~ # /opt/etc/init.d/S51tpws version
tpws-keenetic version: 1.0.9
```

```
~ # /opt/etc/init.d/S51tpws restart
Stopping TPWS service...
Bind to local interface: br0
Loading hostlist /opt/etc/tpws/user.list
loading plain text list
Loaded 31 hosts from /opt/etc/tpws/user.list
Started TPWS service
```
```
~ # cat /opt/etc/tpws/tpws.conf
`# Local network interface, e.g. br0
# You can specify multiple interfaces separated by space, e.g. LOCAL_INTERFACE="br0 nwg0"
LOCAL_INTERFACE="br0"

# All arguments here: https://github.com/bol-van/zapret (search for `tpws` on the page)
TPWS_ARGS="--bind-wait-ip=10 --disorder --tlsrec=sni --split-http-req=method --split-pos=2"
TPWS_EXTRA_ARGS="--hostlist=/opt/etc/tpws/user.list"

BIND_PORT=999
IPV6_ENABLED=1
PIDFILE=/opt/var/run/tpws.pid`
```
```
~ # ps | grep tpws
14654 21474836   428 S    /opt/usr/bin/tpws --daemon --bind-iface4=br0 --port=999 --pidfile=/opt/var/run/tpws.pid --bind-wait-ip=10 --disorder --tlsrec=sni --split-http-req=method --split-
15033 root      5328 S    grep tpws
```

```
~ # iptables-save | grep 999
-A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p udp -m udp --dport 443 -j REDIRECT --to-ports 999

```

**Comment by Seamas73** [comment]
Стоило в /opt/bin/S51tpws строку:
`BIND_IFACE="$BIND_IFACE --bind-iface4=$IFACE"`
заменить на строку:
`BIND_IFACE="$BIND_IFACE --bind-iface4=$IFACE --bind-iface6=$IFACE"`,
как проблема с обновлением OpenWRT на сетевом диске пропала - списки пакетов загружаются с downloads.openwrt.org без ошибок. 
Кроме того, снова влёт стали обновляться приложения в Google Play Market-e: раньше надо было несколько раз запустить/отменить/запустить обновление приложения, чтобы оно стало загружаться и устанавливаться, при этом несмотря на тариф 500 Мбит/с загрузка шла с тормозами. А теперь только нажал обновить - раз, и приложение уже загрузилось и установилось.

**Comment by Anonym-tsk** [comment]
Вот спасибо, никто раньше не заметил.
Добавил исправление в версии 1.0.10

**Comment by Seamas73** [comment]
А перед выполнением команды "BIND_IFACE=" разве не надо делать проверку, включён ли в tpws.conf IPv6, и в зависимости от того включён или нет, добавлять или не добавлять флаг "--bind-iface6=$IFACE"?

**Comment by Anonym-tsk** [comment]
Технически, в этом нет необходимости. Но я уже тоже подумал об этом, добавлю.
