### ISSUE TITLE
Не правильный фаервол

### ISSUE THREAD

**Issue by DennoN-RUS** [Anonym-tsk/tpws-keenetic#2]
Возможно в скрипте etc/ndm/netfilter.d/100-tpws.sh
стоит в for цикле перед каждым выполнением iptables -t nat делать еще раз if c проверкой, что такого правила нет. а то ipstables позволяет добавлять одни и те же строки
![изображение](https://github.com/user-attachments/assets/b552dd91-335f-4c70-970d-86001841c0f3)

**Comment by Anonym-tsk** [comment]
Так перед циклом есть проверка, зачем еще и в цикле это делать?

**Comment by DennoN-RUS** [comment]
А, да, там проверка по последнему порту и если ни одного правила с ним не найдено, то доабвляется. Не так прочитал условие)
