### ISSUE TITLE
Ошибка сети при запуске приложения на телевизоре Samsung (Tizen)

### ISSUE THREAD

**Issue by perosnamjl** [Anonym-tsk/tpws-keenetic#4]
**Опишите проблему**
При запуске приложения YouTube вылет и ошибка сети, либо серый/черный экран

**Модель маршрутизатора**
Keenetic Giga (KN-1011), Версия ОС
4.1.7

**Выполните команды и приложите их вывод**
`cat /opt/etc/tpws/tpws.conf`
```
> ~ # cat /opt/etc/tpws/tpws.conf
# Local network interface, e.g. br0
# You can specify multiple interfaces separated by space, e.g. LOCAL_INTERFACE="br0 nwg0"
LOCAL_INTERFACE="br0"

# All arguments here: https://github.com/bol-van/zapret (search for tpws on the page)
TPWS_ARGS="--bind-wait-ip=10 --disorder --tlsrec=sni --split-http-req=method --split-pos=2"
TPWS_EXTRA_ARGS="--hostlist=/opt/etc/tpws/user.list --hostlist-auto=/opt/etc/tpws/auto.list"

BIND_PORT=999
PIDFILE=/opt/var/run/tpws.pid
```

`ps | grep tpws`
```
> 10654 21474836   460 S    /opt/usr/bin/tpws --daemon --bind-iface4=br0 --port
11333 root      5400 S    grep tpws
```

`iptables-save | grep 999`
```
> -A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p udp -m udp --dport 443 -j REDIRECT --to-ports 999
```

**Comment by Anonym-tsk** [comment]
Добавьте в файл `/opt/etc/tpws/user.list`
```
youtube.com
youtu.be
yt4.ggpht.com
yt4.googleusercontent.com
youtubei.googleapis.com
gvt1.com
gstatic.com
```
Перезапустите сервис
`/opt/etc/init.d/S51tpws restart`
сообщите о результатах

**Comment by perosnamjl** [comment]
Не помогло, все также серый экран и вылет с ошибкой сети.

**Comment by Anonym-tsk** [comment]
Можно попробовать заблокировать QUIC вообще
> Создаём в веб-интерфейсе роутера правило файерволла, блокирующее протокол QUIC:
> Межсетевой экран → Домашняя сеть → Добавить правило
> Включить правило: Включено
> Описание: Блокировать QUIC
> Действие: Запретить
> Протокол: UDP
> Номер порта назначения: Равен 443
> Остальные параметры оставляем без изменений

**Comment by mslordsm** [comment]
**Опишите проблему**
Аналогичная проблема.
на LG с TIZEN и Sony с андроидТВ приложения ютуб выдают ошибку.
на компьютере ютуб открывается и показывает.

**Модель маршрутизатора:** Keenetic Ultra II
**Версия ОС** 3.5.10

**Выполните команды и приложите их вывод**

`cat /opt/etc/tpws/tpws.conf`
# Local network interface, e.g. br0
# You can specify multiple interfaces separated by space, e.g. LOCAL_INTERFACE="br0 nwg0"
LOCAL_INTERFACE="br0"

# All arguments here: https://github.com/bol-van/zapret (search for `tpws` on the page)
TPWS_ARGS="--bind-wait-ip=10 --disorder --tlsrec=sni --split-http-req=method --split-pos=2"
TPWS_EXTRA_ARGS="--hostlist=/opt/etc/tpws/user.list --hostlist-auto=/opt/etc/tpws/auto.list --hostlist-auto-debug=/opt/var/log/tpws.log --hostlist-exclude=/opt/etc/tpws/exclude.list"

BIND_PORT=999
PIDFILE=/opt/var/run/tpws.pid

`ps | grep tpws`
 4062 21474836   464 R    /opt/usr/bin/tpws --daemon --bind-iface4=br0 --port 999 --pidfile /opt/var/run/tpws.pid --bind-wait-ip=10 --disorder --tlsrec=sni --split-http-req=method --split-pos=2 --hostlist=/opt/etc/tpws/user.list --host
 4547 root      5400 S    grep tpws

`iptables-save | grep 999`
-A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p udp -m udp --dport 443 -j REDIRECT --to-ports 999

**Провайдер:** Билайн

блокировку quic в межсетевом экране пробовал

**Comment by perosnamjl** [comment]
> Можно попробовать заблокировать QUIC вообще
> 
> > Создаём в веб-интерфейсе роутера правило файерволла, блокирующее протокол QUIC:
> > Межсетевой экран → Домашняя сеть → Добавить правило
> > Включить правило: Включено
> > Описание: Блокировать QUIC
> > Действие: Запретить
> > Протокол: UDP
> > Номер порта назначения: Равен 443
> > Остальные параметры оставляем без изменений
> 
> Какой у вас провайдер?

Билайн

**Comment by Anonym-tsk** [comment]
У меня на Android TV сегодня тоже отвалилось. Ищем решение

**Comment by filkint** [comment]
> У меня на Android TV сегодня тоже отвалилось. Ищем решение

На вас вся надежда!

**Comment by con05** [comment]
На AndroidTV пока вхожу так:
- останавливаю tpws на роутере
- останавливаю youtube на ТВ
- запускаю youtube на ТВ
- пока крутится кружок подключения, запускаю tpws на роутере
После этих действий youtube загружается и не тормозит. Через какое-то время приходится повторять.

**Comment by freemlab** [comment]
Аналогичная проблема с ТВ Samsung  на Tyzen

**Comment by perosnamjl** [comment]
пишут, что помогает убрать строку `youtube.com` в user.list, но видео могут не запускаться

**Comment by Anonym-tsk** [comment]
> пишут, что помогает убрать строку `youtube.com` в user.list, но видео могут не запускаться. Пока не проверял.

Как-то не очень помогает..

**Comment by Anonym-tsk** [comment]
Обновить скрипты, если еще не
В `exclude.list` добавить
```
google.com
dns.google
youtube.com
youtu.be
```
Из `user.list` и `auto.list` соответственно удалить
У меня на Android TV заработало

**Comment by Fermi37** [comment]
> Обновить скрипты, если еще не В `exclude.list` добавить
> 
> ```
> google.com
> dns.google
> youtube.com
> youtu.be
> ```
> 
> Из `user.list` и `auto.list` соответственно удалить У меня на Android TV заработало

На Apple TV заработало

**Comment by mslordsm** [comment]
Да, тоже заработало на тв

**Comment by SPIRITUFA** [comment]
> Обновить скрипты, если еще не В `exclude.list` добавить
> 
> ```
> google.com
> dns.google
> youtube.com
> youtu.be
> ```
> 
> Из `user.list` и `auto.list` соответственно удалить У меня на Android TV заработало

Уточню, для этого режим переводим в ALL?

**Comment by Anonym-tsk** [comment]
> для этого режим переводим в ALL?

Нет, auto или list

**Comment by perosnamjl** [comment]
Тоже заработало, в аккаунт входит конечно крайне медленно. Как будто скорости не хватает. Левое меню иногда долго грузит.

**Comment by filkint** [comment]
> Тоже заработало, в аккаунт входит конечно крайне медленно. Как будто скорости не хватает. Левое меню иногда долго грузит (либо его вообще нет при запуске) Ну и задержка на запуск видео секунд 10 ну и также в плеере описание, рекомендации и заголовки просто иногда не грузит, пусто как будто). Плейлисты вообще не грузит.
> 
> В разделе подписки тоже элементы долго грузятся. Короче пока так 😅

В LG TV тоже самое.

**Comment by rustedmind** [comment]
Если добавить youtube.com в exclude.list, то на телевизоре приложение будет медленно, но работать. Правда, ютуб перестанет открываться на десктопе. Не уверен, что поможет, но вот дамп пакетов с телевизора при открытии приложения.
[capture-Bridge0-Aug  9 14-53-31.zip](https://github.com/user-attachments/files/16560790/capture-Bridge0-Aug.9.14-53-31.zip)
мой конфиг user.list:
```
/opt/etc/init.d # cat /opt/etc/tpws/user.list
youtube.com
you.tube
yt.be
ytimg.com
gstatic.com
googleapis.com
googlevideo.com
i.ytimg.com
i9.ytimg.com
yt3.ggpht.com
yt3.googleusercontent.com
yt4.ggpht.com
yt4.googleusercontent.com
youtubei.googleapis.com
gvt1.com
ntc.party
youtubei.googleapis.com
ytimg.l.google.com
nhacmp3youtube.com
googleusercontent.com
ggpht.com
/opt/etc/init.d #
```

**Comment by mslordsm** [comment]
на компьютерах и телевизоре с андроид тв работает, если убрать из исключений youtube.com и youtu.be, а поставить их в юзер лист.
на приставке с андроид тв и телевизоре lg не работает ни при таких листах, ни при каких-либо других.

если запустить на lg (или приставке) ютуб, потом перезапустить tpws, может заработать до следующей перезагрузки с вероятностью 1 из 3.

**Comment by ykmn** [comment]
МГТС, Keenetic Viva (KN-1910), содержимое user.list и exclude.list по умолчанию, tpws в режиме auto, QUIC в роутере не заблокирован.

В браузере компьютера работает; в мобильном приложении работает.
На Apple TV - приложение очень долго запускается, видео показывает нормально, но не отображает ни название, ни комментарии.
На Samsung Tiven - приложение ооооочень долго запускается (минут 10), сначала показало только меню, потом частично превьюшки. Если видео удалось открыть, воспроизводит нормально, но тоже без названия и комментариев.

**Comment by ReMicroN** [comment]
На Keenetic KN-1811 работает без отключения HWNAT ("Сетевой ускоритель" в пакетах), OPKG на встроенной памяти. Установил в режиме "list". YouTube работает на ПК и Android, но полностью не работает на ТВ Hisense U8HQ - приложение даже сеть не видит, хотя с остальными приложениями все нормально.

**Comment by Anonym-tsk** [comment]
Можно попробовать вместо tpws использовать nfqws. Он пока не работает с автоматическими списками, но в целом почти готов
https://github.com/Anonym-tsk/nfqws-keenetic

**Comment by ReMicroN** [comment]
> Можно попробовать вместо tpws использовать nfqws. Он пока не работает с автоматическими списками, но в целом почти готов https://github.com/Anonym-tsk/nfqws-keenetic

А какой лучше? Можете коротко рассказать?

**Comment by Anonym-tsk** [comment]
> А какой лучше?

Ну как вам сказать. С tpws у меня на данный момент работает или телевизор, или браузер. С текущей конфигурацией [nfqws](https://github.com/Anonym-tsk/nfqws-keenetic) работает и там, и там, и не тормозит.

**Comment by filkint** [comment]
> С текущей конфигурацией [nfqws](https://github.com/Anonym-tsk/nfqws-keenetic) работает и там, и там, и не тормозит.

Вау! Неужели победа?

**Comment by Anonym-tsk** [comment]
> Нужен IPv6 от провайдера?

Не нужен. Просто нужный компонент на кинетиках не устанавливается без компонента IPv6

**Comment by filkint** [comment]
> Можно попробовать вместо tpws использовать nfqws. Он в целом почти готов https://github.com/Anonym-tsk/nfqws-keenetic

К сожалению вообще не работает не в браузере не на тв.

**Comment by Anonym-tsk** [comment]
> К сожалению вообще не работает не в браузере не на тв.

А точно установили нужные пакеты? IPv6 и Netfilter

**Comment by filkint** [comment]
> А точно установили нужные пакеты? IPv6 и Netfilter

Точно точно. Я поставил еще когда twps устанавливал.

**Comment by Anonym-tsk** [comment]
Отключите IPv6 на провайдере

**Comment by filkint** [comment]
> Отключите IPv6 на провайдере

Извините за глупый вопрос, на прошивке 2.16 это где?

**Comment by filkint** [comment]
Я не знаю есть ли на tizen msx, но на lg через msx работает.

**Comment by acidroper** [comment]
> Отключите IPv6 на провайдере

А если добавить аналогичные правила в `ip6tables`, оно заработает для IPv6?

**Comment by acidroper** [comment]
> > Отключите IPv6 на провайдере
> 
> А если добавить аналогичные правила в `ip6tables`, оно заработает для IPv6?

Отвечаю на свой вопрос: попробовал — работает. 

@Anonym-tsk Может, стоит добавить поддержку IPv6, чтобы можно было обойтись без его отключения? Если нет никаких подводных камней, могу создать PR.

**Comment by Anonym-tsk** [comment]
> могу создать PR.

Буду признателен

**Comment by Riadner** [comment]
> > > Отключите IPv6 на провайдере
> > 
> > 
> > А если добавить аналогичные правила в `ip6tables`, оно заработает для IPv6?
> 
> Отвечаю на свой вопрос: попробовал — работает.
> 
> @Anonym-tsk Может, стоит добавить поддержку IPv6, чтобы можно было обойтись без его отключения? Если нет никаких подводных камней, могу создать PR.

Тоже хотелось увидеть поддержку IPv6 совместно с IPv4. Было бы идеально.
Подскажи как добавил в правила для ip6tables? Устанавливать "Модули ядра подсистемы Netfilter" нужно дополнительно?

**Comment by acidroper** [comment]
> > могу создать PR.
> 
> Буду признателен

Создал: https://github.com/Anonym-tsk/tpws-keenetic/pull/8

**Comment by acidroper** [comment]
@Riadner 
> Подскажи как добавил в правила для ip6tables?

Можно посмотреть тут https://github.com/Anonym-tsk/tpws-keenetic/pull/8.

> Устанавливать "Модули ядра подсистемы Netfilter" нужно дополнительно?

Думаю, нужно. Но они у меня уже были установлены.

**Comment by grom5555** [comment]
> Можно попробовать вместо tpws использовать nfqws. Он в целом почти готов https://github.com/Anonym-tsk/nfqws-keenetic

Если уже установлен tpws, могу его выключить и рядом поставить nfqws? Или лучше с нуля, почистить дисковое пространство и установить nfqws?

**Comment by Anonym-tsk** [comment]
Поддержка IPv6 добавлена

**Comment by Anonym-tsk** [comment]
> Если уже установлен tpws, могу его выключить и рядом поставить nfqws?

Лучше удалить один и поставить другой.
Но вообще, они могут и вместе работать

**Comment by Anonym-tsk** [comment]
@perosnamjl проблема решена?

**Comment by perosnamjl** [comment]
Да, сменой на nfqws
