### ISSUE TITLE
Сайты из списка user.list не открываются через VPN соединение, настроенное на роутере (l2tp)

### ISSUE THREAD

**Issue by IAtwood** [Anonym-tsk/tpws-keenetic#9]
При соединении по VPN (l2tp) к домашней сети, сайты из списка для обхода ограничений не работают

**Модель маршрутизатора**
Укажите полную модель роутера и прошивку
keenetic giga 1011
**Выполните команды и приложите их вывод**
`cat /opt/etc/tpws/tpws.conf`
```
# Local network interface, e.g. br0
# You can specify multiple interfaces separated by space, e.g. LOCAL_INTERFACE="br0 nwg0"
LOCAL_INTERFACE="br0"

# All arguments here: https://github.com/bol-van/zapret (search for `tpws` on the page)
TPWS_ARGS="--bind-wait-ip=5 --disorder --hostnospace --domcase --tlsrec=sni --split-http-req=method --split-pos=2"
TPWS_EXTRA_ARGS="--hostlist=/opt/etc/tpws/user.list"

BIND_PORT=999
PIDFILE=/opt/var/run/tpws.pid
```

`ps | grep tpws`
```
 9256 21474836   420 S    /opt/usr/bin/tpws --daemon --bind-iface4=br0 --port 999 --pidfile /opt/v
27282 root      5400 S    grep tpws
```

`iptables-save | grep 999`
```
-A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 999
-A PREROUTING -i br0 -p udp -m udp --dport 443 -j REDIRECT --to-ports 999
```

**Comment by Anonym-tsk** [comment]
У вас интерфейс только br0 указан. Добавьте интерфейс вашего впн и все заработает

**Comment by IAtwood** [comment]
Здравствуйте.
l2tp0 добавлял, лучше точно не стало. Вроде он такой был
--
Отправлено из Mail.ru для Android понедельник, 12 августа 2024г., 17:06 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by Anonym-tsk** [comment]
`ip addr show` и ищите ваш интерфейс. После этого сервис перезапустите. Проверял лично с wireguard, все работало.

**Comment by IAtwood** [comment]
Не работает, играл интерфейсами.
У вас наверно внешний сервер, к которому цепляется кинетик, а у меня на самом кинетике поднят. Мне нужно мой домашний интернет вместе с этой чудо программой прокинуть на мой телефон, чтобы интернет на нем был без ограничений
--
Отправлено из Mail.ru для Android понедельник, 12 августа 2024г., 17:18 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by IAtwood** [comment]
Не очень понятно какой точно интерфейс указывать...
BusyBox v1.36.1 (2024-03-19 14:07:09 UTC) built-in shell (ash)
~ # ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ***@***.***: <NOARP> mtu 1480 qdisc noop qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ***@***.***: <NOARP> mtu 1480 qdisc noop qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
4: ***@***.***: <NOARP> mtu 1476 qdisc noop qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
5: ***@***.***: <BROADCAST,MULTICAST> mtu 1462 qdisc noop qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: ***@***.***: <BROADCAST,MULTICAST> mtu 1458 qdisc noop qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop qlen 1000
    link/ether 56:79:aa:16:03:ed brd ff:ff:ff:ff:ff:ff
8: ***@***.***: <NOARP> mtu 1452 qdisc noop qlen 1
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
9: ezcfg0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether 9e:40:61:67:93:62 brd ff:ff:ff:ff:ff:ff
    inet 78.47.125.180/32 brd 78.255.255.255 scope global ezcfg0
       valid_lft forever preferred_lft forever
10: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 2000
    link/ether 50:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:feae:258b/64 scope link
       valid_lft forever preferred_lft forever
11: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 2000
    link/ether 2c:56:dc:74:c3:f5 brd ff:ff:ff:ff:ff:ff
    inet 195.14.48.193/24 brd 195.14.48.255 scope global eth3
       valid_lft forever preferred_lft forever
    inet6 fe80::2e56:dcff:fe74:c3f5/64 scope link
       valid_lft forever preferred_lft forever
12: ra0: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master br0 qlen 1000
    link/ether 50:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
13: ra1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master br1 qlen 1000
    link/ether 52:ff:20:1e:25:8b brd ff:ff:ff:ff:ff:ff
14: ra2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master br2 qlen 1000
    link/ether 52:ff:20:2e:25:8b brd ff:ff:ff:ff:ff:ff
15: ra3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:3e:25:8b brd ff:ff:ff:ff:ff:ff
16: ra4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:4e:25:8b brd ff:ff:ff:ff:ff:ff
17: ra5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:5e:25:8b brd ff:ff:ff:ff:ff:ff
18: ra6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:6e:25:8b brd ff:ff:ff:ff:ff:ff
19: ra7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether 52:ff:20:7e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7e:258b/64 scope link
       valid_lft forever preferred_lft forever
20: ra8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 qlen 1000
    link/ether 52:ff:20:8e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe8e:258b/64 scope link
       valid_lft forever preferred_lft forever
21: ra9: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master br1 qlen 1000
    link/ether 52:ff:20:9e:25:8b brd ff:ff:ff:ff:ff:ff
22: ra10: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
23: ra11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br3 qlen 1000
    link/ether 52:ff:20:be:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:febe:258b/64 scope link
       valid_lft forever preferred_lft forever
24: ra12: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:ce:25:8b brd ff:ff:ff:ff:ff:ff
25: ra13: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:de:25:8b brd ff:ff:ff:ff:ff:ff
26: ra14: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:ee:25:8b brd ff:ff:ff:ff:ff:ff
27: ra15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether 52:ff:20:fe:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefe:258b/64 scope link
       valid_lft forever preferred_lft forever
28: apcli0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 56:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
29: apcli1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 5a:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
30: ntce0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether ae:8e:1c:18:ef:41 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ac8e:1cff:fe18:ef41/64 scope link
       valid_lft forever preferred_lft forever
31: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0
    link/ether 50:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:feae:258b/64 scope link
       valid_lft forever preferred_lft forever
32: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br2
    link/ether 52:ff:20:ae:25:89 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:feae:2589/64 scope link
       valid_lft forever preferred_lft forever
33: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1
    link/ether 52:ff:20:ae:25:8a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:feae:258a/64 scope link
       valid_lft forever preferred_lft forever
34: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br3
    link/ether 52:ff:20:ae:25:88 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:feae:2588/64 scope link
       valid_lft forever preferred_lft forever
35: cdc_br1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether 52:ed:0f:60:36:18 brd ff:ff:ff:ff:ff:ff
36: qmi_br0: <BROADCAST,POINTOPOINT,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 6a:a5:fb:a7:9b:c3 peer ff:ff:ff:ff:ff:ff
    inet 10.206.192.63/25 scope global qmi_br0
       valid_lft forever preferred_lft forever
    inet6 fe80::68a5:fbff:fea7:9bc3/64 scope link
       valid_lft forever preferred_lft forever
37: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 50:ff:20:ae:25:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fd10:3b7f:eea6:0:52ff:20ff:feae:258b/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::52ff:20ff:feae:258b/64 scope link
       valid_lft forever preferred_lft forever
38: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 52:ff:20:ae:25:8a brd ff:ff:ff:ff:ff:ff
    inet 10.1.30.1/24 brd 10.1.30.255 scope global br1
       valid_lft forever preferred_lft forever
    inet6 fe80::50ff:20ff:feae:258a/64 scope link
       valid_lft forever preferred_lft forever
39: br2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 52:ff:20:ae:25:89 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global br2
       valid_lft forever preferred_lft forever
    inet6 fe80::50ff:20ff:feae:2589/64 scope link
       valid_lft forever preferred_lft forever
40: br3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 52:ff:20:ae:25:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.1/24 brd 192.168.3.255 scope global br3
       valid_lft forever preferred_lft forever
    inet6 fe80::50ff:20ff:feae:2588/64 scope link
       valid_lft forever preferred_lft forever
41: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 qlen 1000
    link/ether 52:ff:20:7e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7e:258b/64 scope link
       valid_lft forever preferred_lft forever
42: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 qlen 1000
    link/ether 52:ff:20:fe:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefe:258b/64 scope link
       valid_lft forever preferred_lft forever
43: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 qlen 1000
    link/ether 52:ff:20:7e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7e:258b/64 scope link
       valid_lft forever preferred_lft forever
44: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 qlen 1000
    link/ether 52:ff:20:fe:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefe:258b/64 scope link
       valid_lft forever preferred_lft forever
45: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br2 qlen 1000
    link/ether 52:ff:20:7e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7e:258b/64 scope link
       valid_lft forever preferred_lft forever
46: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br2 qlen 1000
    link/ether 52:ff:20:fe:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefe:258b/64 scope link
       valid_lft forever preferred_lft forever
47: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br3 qlen 1000
    link/ether 52:ff:20:7e:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7e:258b/64 scope link
       valid_lft forever preferred_lft forever
48: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br3 qlen 1000
    link/ether 52:ff:20:fe:25:8b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefe:258b/64 scope link
       valid_lft forever preferred_lft forever
49: wwan0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc cake master qmi_br0 qlen 1000
    link/[65534]
    inet6 fe80::96a0:d90b:701:2aa7/64 scope link flags 800
       valid_lft forever preferred_lft forever
50: l2tp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1400 qdisc fq_codel qlen 3
    link/ppp
    inet 192.168.1.1 peer 192.168.1.200/32 scope global l2tp0
       valid_lft forever preferred_lft forever

--
Отправлено из Mail.ru для Android понедельник, 12 августа 2024г., 17:18 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by Anonym-tsk** [comment]
В конфиг впишите "br0 l2tp0" и проверьте.


> У вас наверно внешний сервер

Нет, у меня на кинетике WG и я к нему подключаюсь снаружи

**Comment by IAtwood** [comment]
Так пробовал. Не работает. Более того, кинетик отваливается от интернета, соответственно интернета в сети уже нет. Единственный способ вернуть настройки, подключиться к нему  по внутренней сети.
--
Отправлено из Mail.ru для Android вторник, 13 августа 2024г., 14:08 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by IAtwood** [comment]
А какой интерфейс на wireguard, и каким приложением с телефона подключаться? Может просто на него перейти
--
Отправлено из Mail.ru для Android вторник, 13 августа 2024г., 14:08 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by Anonym-tsk** [comment]
На wireguard интерфейс nwg0
Подключаться приложением WireGuard.

У вас кажется подсети для локальной сети и для VPN пересекаются. Вижу 192.168.1.1 и там, и там.
Можете попробовать для VPN сделать другую.

**Comment by IAtwood** [comment]
Да, верно. Была другая подсеть. С доступом в сегмент сети домашней сети. Не работал интернет как нужно, тогда диапазон сети выбрал того сегмента, но со сдвигом. Легче не стало. Работает только доступ к локальной сети.
У вас с wireguard скорость обмена высокая с устройствами домашней сети? На l2tp мне кажется уж больно низкая
--
Отправлено из Mail.ru для Android вторник, 13 августа 2024г., 14:19 +03:00 от Nikolay Vasilchuk  ***@***.*** :

**Comment by Anonym-tsk** [comment]
wireguard побыстрее l2tp точно

**Comment by IAtwood** [comment]
Поднял WG. Подключение есть. Залоченные сайты так и не работают через впн. Доступ к локальным ресурсам отсутствует.
--
Отправлено из Mail.ru для Android вторник, 13 августа 2024г., 14:19 +03:00 от Nikolay Vasilchuk  ***@***.*** :

>На wireguard интерфейс nwg0
>Подключаться приложением WireGuard.
>У вас кажется подсети для локальной сети и для VPN пересекаются. Вижу 192.168.1.1 и там, и там.
>Можете попробовать для VPN сделать другую.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>
# Local network interface, e.g. br0
# You can specify multiple interfaces separated by space, e.g. LOCAL_INTERFACE="br0 nwg0"
LOCAL_INTERFACE="br0 nwg0"

# All arguments here: https://github.com/bol-van/zapret (search for `tpws` on the page)
TPWS_ARGS="--bind-wait-ip=5 --disorder --hostnospace --domcase --split-http-req=method --tlsrec=sni --split-pos=2"
TPWS_EXTRA_ARGS="--hostlist=/opt/etc/tpws/user.list"

BIND_PORT=999
PIDFILE=/opt/var/run/tpws.pid

**Comment by IAtwood** [comment]
Все, настроил. И интернет работает, и к локалке подключился. Спасибо
--
Отправлено из Mail.ru для Android вторник, 13 августа 2024г., 16:50 +03:00 от Nikolay Vasilchuk  ***@***.*** :
